// Mock data for the application
import { Novel } from "./types";

export const mockNovels: Novel[] = [
  {
    id: "1",
    slug: "madman-family",
    title: "I Am The Madman Of This Family",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Solver Keter",
    rating: 4.5,
    totalRatings: 11,
    categories: ["Adventure", "Fantasy", "Action"],
    description:
      'Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!... Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...Solver Keter, one of the Five Lunatics of Lawless City, regresses to when he was the illegitimate son of a doomed archery family. "If I regressed and couldn\'t even save my family, I might as well go kill myself." For my family? No, for my freedom!...',
    updatedAt: "8 hours ago",
    chapterCount: 46,
    language: "Chinese",
    status: "ongoing",
    yearOfRelease: 2022,
    tags: ["Regression", "Family", "Revenge"],
  },
  {
    id: "2",
    slug: "industrial-cthulhu",
    title: "Industrial Cthulhu: Starting as an Island Lord",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Unknown Author",
    rating: 4.2,
    totalRatings: 21,
    categories: [
      "Adventure",
      "Fantasy",
      "Historical",
      "Horror",
      "Mystery",
      "Supernatural",
      "Tragedy",
      "Action",
    ],
    description:
      '"I saw with my own eyes that they used the finest, rustproof refined steel to make utensils and cans, filling them with just a little food, then casually throwing them away after eating." "I saw with my own eyes that they used giant beasts as tall as mountains to devour soil and rocks, digging out..."',
    updatedAt: "8 hours ago",
    chapterCount: 42,
    language: "English",
    status: "ongoing",
    yearOfRelease: 2023,
    tags: ["Evil Gods", "System", "Island Development"],
  },
  {
    id: "3",
    slug: "genius-cloning",
    title: "The Genius of Cloning in the Academy City",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Unknown Author",
    rating: 4.7,
    totalRatings: 19,
    categories: [
      "Comedy",
      "Psychological",
      "Gender Bender",
      "Fantasy",
      "Supernatural",
      "Adventure",
      "Martial Arts",
    ],
    description:
      "I awoke as Violet, a familiar villainess trapped in a shady corporate research lab. Screw this! With my unstoppable cloning technique, I'm getting out of here and going to the Academy to live my own life!...",
    updatedAt: "3 hours ago",
    chapterCount: 23,
    language: "Japanese",
    status: "ongoing",
    yearOfRelease: 2024,
    tags: ["Reincarnation", "Academy", "Cloning", "Female Protagonist"],
  },
  {
    id: "4",
    slug: "lord-mysteries",
    title: "Lord of the Mysteries",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Cuttlefish That Loves Diving",
    rating: 4.7,
    totalRatings: 853,
    categories: ["Fantasy", "Mystery", "Supernatural"],
    description:
      "With the rising tide of steam power and machinery, who can come close to being a Beyonder? Shrouded in the fog of history and darkness, who or what is the lurking evil that murmurs into our ears?",
    updatedAt: "2 days ago",
    chapterCount: 1430,
    language: "Chinese",
    status: "completed",
    yearOfRelease: 2018,
    tags: ["Gods", "Steampunk", "Mystery", "Lovecraftian"],
  },
  {
    id: "5",
    slug: "legendary-mechanic",
    title: "The Legendary Mechanic",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Chocolion",
    rating: 4.7,
    totalRatings: 712,
    categories: ["Sci-Fi", "Adventure", "Fantasy"],
    description:
      "What would a regular old-school game player do when he's transported into a futuristic virtual game world filled with spaceships, wormholes, advanced technology, and superpowers?",
    updatedAt: "1 day ago",
    chapterCount: 1465,
    language: "Chinese",
    status: "completed",
    yearOfRelease: 2017,
    tags: ["Game Elements", "Mecha", "Space"],
  },
  {
    id: "6",
    slug: "shadow-slave",
    title: "Shadow Slave",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Guiltythree",
    rating: 4.1,
    totalRatings: 769,
    categories: ["Fantasy", "Action", "Adventure"],
    description:
      "Growing up in poverty, Sunny never expected anything good from life. However, even he did not anticipate being chosen by the Nightmare Spell and becoming one of the Awakened - an elite group of people gifted with supernatural powers.",
    updatedAt: "12 hours ago",
    chapterCount: 852,
    language: "English",
    status: "ongoing",
    yearOfRelease: 2020,
    tags: ["System", "Cultivation", "Dark"],
  },
  {
    id: "7",
    slug: "circle-inevitability",
    title: "Circle of Inevitability",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Cuttlefish That Loves Diving",
    rating: 4.6,
    totalRatings: 528,
    categories: ["Fantasy", "Mystery", "Supernatural"],
    description:
      "A mysterious world filled with Beyonders and extraordinary abilities. Follow the protagonist as they navigate through the intricate web of secrets and powers.",
    updatedAt: "3 days ago",
    chapterCount: 745,
    language: "Chinese",
    status: "ongoing",
    yearOfRelease: 2021,
    tags: ["Gods", "Mystery", "Beyonder"],
  },
  {
    id: "8",
    slug: "top-tier-providence",
    title: "Top Tier Providence, Secretly Cultivate for a Thousand Years",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Ren Wo Xiao",
    rating: 4.5,
    totalRatings: 542,
    categories: ["Fantasy", "Adventure", "Martial Arts"],
    description:
      "Han Jue was transmigrated into a cultivation world with an almost omnipotent system. However, he quickly discovered that offending even a single person could lead to unimaginable consequences.",
    updatedAt: "5 days ago",
    chapterCount: 1024,
    language: "Chinese",
    status: "ongoing",
    yearOfRelease: 2019,
    tags: ["Cultivation", "System", "Cautious Protagonist"],
  },
  {
    id: "9",
    slug: "three-wives",
    title: "My Three Wives Are Beautiful Vampires",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "Victor_Weismann",
    rating: 4.1,
    totalRatings: 587,
    categories: ["Fantasy", "Romance", "Supernatural", "Harem"],
    description:
      "Victor was a normal young man who was visiting a night club until it was attacked by vampires. When he wakes up, he finds himself in the house of a vampire ready to be sacrificed.",
    updatedAt: "1 day ago",
    chapterCount: 635,
    language: "English",
    status: "ongoing",
    yearOfRelease: 2020,
    tags: ["Vampire", "Harem", "Romance"],
  },
  {
    id: "10",
    slug: "cultivation-online",
    title: "Cultivation Online",
    coverImage:
      "https://ranobes.top/uploads/posts/2025-03/thumbs/1741422661_i-am-the-madman-of-this-family.webp",
    author: "MyLittleBrother",
    rating: 3.6,
    totalRatings: 579,
    categories: ["Fantasy", "Adventure", "Martial Arts", "Virtual Reality"],
    description:
      "Yuan was born with an incurable illness that left him blind at a young age and crippled a few years later, rendering everything below his head useless. Deemed hopeless and irredeemable, his parents abandoned him, and soon after, he lost his will to live.",
    updatedAt: "2 days ago",
    chapterCount: 420,
    language: "English",
    status: "ongoing",
    yearOfRelease: 2021,
    tags: ["Cultivation", "Game Elements", "Virtual Reality"],
  },
];

// Recent updates for the update tape
export const recentUpdates = [
  {
    slug: "lord-void",
    title: "The Lord of Void and Real",
    chapter: "Chapter 319: Three Stars Demolishing Demons",
    updatedAt: "9 minutes ago",
  },
  {
    slug: "beast-taming",
    title: "Beast Taming Patrol",
    chapter: "Chapter 674: Youyou Advances!",
    updatedAt: "14 minutes ago",
  },
  {
    slug: "disciple-simulator",
    title: "I Have A Disciple Simulator",
    chapter: "Chapter 911: The Humble Hallucinatory Dark Demon Venerable!",
    updatedAt: "14 minutes ago",
  },
  {
    slug: "grinding-experience",
    title: "I Am Grinding Experience In Another World",
    chapter: "Chapter 671: Return to Qingqiu",
    updatedAt: "15 minutes ago",
  },
  {
    slug: "reversing-life",
    title: "Reversing Life With Item Copy",
    chapter: "Chapter 128: Not Quite Yet",
    updatedAt: "16 minutes ago",
  },
];

// Available categories for filtering
export const availableCategories = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Fantasy",
  "Gender Bender",
  "Historical",
  "Horror",
  "Martial Arts",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Supernatural",
  "Tragedy",
  "Harem",
  "Virtual Reality",
];

// Available tags for filtering
export const availableTags = [
  "Evil Gods",
  "God-human Relationship",
  "Dense Protagonist",
  "Netorare",
  "Reincarnation",
  "System",
  "Game Elements",
  "Cultivation",
  "Modern Day",
  "Vampire",
  "Harem",
  "Romance",
  "Regression",
  "Family",
  "Revenge",
  "Academy",
  "Cloning",
  "Female Protagonist",
  "Gods",
  "Steampunk",
  "Mystery",
  "Lovecraftian",
  "Mecha",
  "Space",
  "Dark",
  "Beyonder",
  "Cautious Protagonist",
  "Virtual Reality",
];

// Available languages
export const languages = ["Chinese", "Korean", "English", "Japanese"];
